#!/usr/bin/env bash
# Phase 6e — Steward Memory (Recall): optional local hybrid search.

# _recall_pick_python — find the first usable python3 (>=3.11) on PATH.
# macOS users typically have `python3` == 3.9 (system) plus python3.12 from
# Homebrew, so blindly using `python3` fails. We try explicit minor-version
# aliases highest-first, then fall back to plain `python3`.
_recall_pick_python() {
  local cand
  for cand in python3.15 python3.14 python3.13 python3.12 python3.11 python3; do
    if have_cmd "$cand"; then
      local v
      v=$("$cand" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo "")
      case "$v" in
        3.11|3.12|3.13|3.14|3.15)
          echo "$cand"
          return 0
          ;;
      esac
    fi
  done
  return 1
}

# _recall_set_memory_flag — write features.memory into $STEWARD_HOME/config.json
# after a successful install so handoff/diagnostics can detect it.
_recall_set_memory_flag() {
  local cfg="$STEWARD_HOME/config.json"
  [[ -f "$cfg" ]] || return 0
  local py="$1"
  "$py" - "$cfg" <<'PY' || true
import json, sys
path = sys.argv[1]
try:
    with open(path) as f:
        data = json.load(f)
except Exception:
    sys.exit(0)
data.setdefault("features", {})["memory"] = "y"
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PY
}

# _recall_render_config — write a config.toml with paths grounded in
# $STEWARD_HOME, instead of copying the generic ~/.steward template verbatim.
# This matters for any custom STEWARD_HOME (testing, alt installs).
_recall_render_config() {
  local dst="$1"
  cat > "$dst" <<EOF
# Recall configuration. Generated by Steward setup; tweak freely.
#
# Resolution order:
#   1. RECALL_CONFIG env var → explicit path
#   2. RECALL_HOME env var   → \$RECALL_HOME/config.toml
#   3. Default               → ~/.steward/recall/config.toml
#
# All paths support ~ and \$VAR expansion.

[index]
db_path   = "$STEWARD_HOME/recall/search.db"
lock_path = "$STEWARD_HOME/recall/index.lock"

[embedding]
# First use downloads ~600MB of weights from Hugging Face. No note contents
# are sent to an embedding API; embedding runs locally.
model           = "Snowflake/snowflake-arctic-embed-l-v2.0"
dim             = 1024
device          = "auto"        # "auto" | "mps" | "cuda" | "cpu"
batch_size      = 8
max_seq_length  = 512
query_prefix    = "query: "
document_prefix = ""

[query_db]
default_limit_cli = 1000
default_limit_mcp = 500
max_limit         = 2000
timeout_seconds   = 10.0

[chunking]
target_tokens  = 300
max_tokens     = 800
overlap_tokens = 50

[search]
rrf_k     = 60
vec_top_k = 50
fts_top_k = 50

[[markdown_sources]]
name       = "steward"
path       = "$STEWARD_HOME"
extensions = [".md", ".txt"]

[exclusions]
dir_names = [
    "node_modules", "vendor", ".venv", "venv", ".git",
    "dist", "build", "__pycache__", ".pytest_cache",
    ".next", ".cache", "embeddings_cache",
]
file_extensions = [
    ".pdf", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg",
    ".mp3", ".mp4", ".mov", ".wav", ".m4a",
    ".zip", ".tar", ".gz", ".tgz", ".bz2",
    ".db", ".sqlite", ".sqlite3",
    ".pyc", ".so", ".dylib",
]
EOF
}

phase_6e_memory() {
  [[ "${STEWARD_FEAT_MEMORY:-n}" != "y" ]] && return 0
  heading "Phase 6e — Steward Memory (Recall)"

  dim "  Recall builds a local search index over your Steward files."
  dim "  All embedding runs locally — note contents are not sent to any API."
  dim "  First install downloads ~600MB of model weights from Hugging Face."
  dim "  Heavy: torch + sentence-transformers ≈ 2GB on disk total."
  dim "  Skip this on lighter machines; Steward works without it."
  dim "  Native Windows is not supported by this phase — use WSL."
  echo

  local proceed
  ask_yn "  proceed with Steward Memory install?" proceed y
  [[ "$proceed" == "y" ]] || { dim "  skipped."; return 0; }

  # --- Python prerequisite ----------------------------------------------------
  local PY
  if ! PY=$(_recall_pick_python); then
    rust "  no Python >= 3.11 found on PATH."
    dim  "    looked for: python3.15, python3.14, python3.13, python3.12, python3.11, python3"
    dim  "    install Python 3.11+ (e.g. 'brew install python@3.12') and re-run."
    return 1
  fi
  local pyver
  pyver=$("$PY" --version 2>&1)
  sage "  using $PY ($pyver)"

  local RECALL_HOME="$STEWARD_HOME/recall"
  ensure_dir "$RECALL_HOME"

  # --- Config -----------------------------------------------------------------
  if [[ -f "$RECALL_HOME/config.toml" ]]; then
    dim "  config.toml already present at $RECALL_HOME/config.toml — keeping"
  else
    _recall_render_config "$RECALL_HOME/config.toml"
    sage "  wrote $RECALL_HOME/config.toml (paths grounded in \$STEWARD_HOME=$STEWARD_HOME)"
  fi

  # --- Optional: add another markdown source ---------------------------------
  local add_more
  ask_yn "  add another folder to index now (e.g. ~/notes)?" add_more n
  if [[ "$add_more" == "y" ]]; then
    local source_path source_name
    ask "    folder path:" source_path ""
    ask "    source name (one word, used in -s filter):" source_name "notes"
    if [[ -n "$source_path" && -n "$source_name" ]]; then
      cat >> "$RECALL_HOME/config.toml" <<EOF

[[markdown_sources]]
name       = "$source_name"
path       = "$source_path"
extensions = [".md", ".txt"]
EOF
      sage "  added markdown source: $source_name → $source_path"
    else
      dim "  empty path or name — skipped"
    fi
  fi

  # --- venv + install ---------------------------------------------------------
  local install_now
  ask_yn "  install Recall Python deps now (creates $RECALL_HOME/.venv)?" install_now y
  if [[ "$install_now" != "y" ]]; then
    dim "  skipped install. Later, run:"
    dim "    $PY -m venv $RECALL_HOME/.venv"
    dim "    $RECALL_HOME/.venv/bin/pip install -e \"$STEWARD_REPO/packages/recall[embeddings]\""
    return 0
  fi

  if [[ -d "$RECALL_HOME/.venv" ]]; then
    dim "  venv already exists at $RECALL_HOME/.venv — reusing"
  else
    if ! "$PY" -m venv "$RECALL_HOME/.venv"; then
      rust "  venv create failed (using $PY)"
      return 1
    fi
    sage "  created venv at $RECALL_HOME/.venv"
  fi

  dim "  installing recall (this may take several minutes — torch is large)…"
  if ! "$RECALL_HOME/.venv/bin/pip" install --quiet --upgrade pip >/dev/null 2>&1; then
    dim "  pip self-upgrade failed (continuing)"
  fi
  # The [embeddings] extra pulls torch + sentence-transformers (~2GB).
  # Without it, the base install is light but cannot embed locally.
  if "$RECALL_HOME/.venv/bin/pip" install -e "$STEWARD_REPO/packages/recall[embeddings]"; then
    sage "  recall installed"
  else
    rust "  pip install failed — see output above"
    return 1
  fi

  # Record memory feature in $STEWARD_HOME/config.json so handoff + later
  # diagnostics know it's enabled.
  _recall_set_memory_flag "$PY"

  # --- First index ------------------------------------------------------------
  echo
  dim "  First index walks your configured folders and downloads embedding model"
  dim "  weights on first use. On a CPU-only laptop this can take many minutes."
  local first_index
  ask_yn "  run first index now?" first_index n
  if [[ "$first_index" == "y" ]]; then
    if RECALL_CONFIG="$RECALL_HOME/config.toml" "$RECALL_HOME/.venv/bin/recall" index --full; then
      sage "  first index complete"
    else
      rust "  first index returned non-zero (you can re-run later)"
    fi
  else
    dim "  skipped. Run later:"
    dim "    RECALL_CONFIG=$RECALL_HOME/config.toml $RECALL_HOME/.venv/bin/recall index --full"
  fi

  # --- MCP registration (print and ask) --------------------------------------
  if [[ "$STEWARD_RUNTIME" == "claude-code" ]]; then
    echo
    dim "  To use Recall from Claude Code, add this stanza to ~/.claude.json"
    dim "  under the \"mcpServers\" key:"
    echo
    cat <<EOF
    "recall": {
      "type": "stdio",
      "command": "$RECALL_HOME/.venv/bin/python",
      "args": ["-m", "recall.mcp_server"],
      "env": {
        "RECALL_CONFIG": "$RECALL_HOME/config.toml"
      }
    }
EOF
    echo
    dim "  Setup does not modify ~/.claude.json automatically — edit it yourself."
  elif [[ "$STEWARD_RUNTIME" == "codex" ]]; then
    echo
    dim "  Codex MCP integration: see your Codex docs. The server runs as:"
    dim "    RECALL_CONFIG=$RECALL_HOME/config.toml $RECALL_HOME/.venv/bin/python -m recall.mcp_server"
  fi

  # --- Scheduling note --------------------------------------------------------
  echo
  dim "  Background indexing is not auto-installed. To schedule, run:"
  dim "    RECALL_CONFIG=$RECALL_HOME/config.toml $RECALL_HOME/.venv/bin/recall index"
  dim "  on a launchd / systemd / cron / Task Scheduler timer. See guides/local-memory.md."

  echo
  sage "  Steward Memory installed."
  dim "    Config:  $RECALL_HOME/config.toml"
  dim "    Search:  RECALL_CONFIG=$RECALL_HOME/config.toml $RECALL_HOME/.venv/bin/recall search '...'"
  dim "    Doctor:  $RECALL_HOME/.venv/bin/recall doctor          # fast checks, no model load"
  dim "             $RECALL_HOME/.venv/bin/recall doctor --model  # also load model"

  return 0
}
